run_title: ''

trainer:
  kwargs:
    gpus: -1
    accelerator: ddp
    max_epochs: 40
    gradient_clip_val: 1
    log_gpu_memory: None
    limit_train_batches: 25000
    val_check_interval: 2600
    log_every_n_steps: 250
    precision: 32
    terminate_on_nan: false
    check_val_every_n_epoch: 1
    num_sanity_val_steps: 8
    replace_sampler_ddp: false
  checkpoint_kwargs:
    verbose: true
    save_top_k: 5
    save_last: true
    period: 1
    monitor: val_ssim_fid100_f1_total_mean
    mode: max
training_model:
  kind: default
  visualize_each_iters: 1000
  concat_mask: true
  store_discr_outputs_for_vis: true
losses:
  l1:
    weight_missing: 0
    weight_known: 10
  perceptual:
    weight: 0
  adversarial:
    kind: r1
    weight: 10
    gp_coef: 0.001
    mask_as_fake_target: true
    allow_scale_mask: true
  feature_matching:
    weight: 100
  segm_pl:
    weight: 0.3
    arch_encoder: resnet50
    imagenet_weights: true
optimizers:
  generator:
    kind: adam
    lr: 0.001
  discriminator:
    kind: adam
    lr: 0.0001

defaults:
  - location: celeba
  - data: abl-04-256-mh-dist-celeba
  - generator: pix2pixhd_global_sigmoid
  - discriminator: pix2pixhd_nlayer
  - visualizer: directory
  - evaluator: default_inpainted
  - hydra: overrides
